apiVersion: v2
name: parallel-ai
description: A Helm chart for Parallel AI System
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/parallel-ai/parallel-ai-system
sources:
  - https://github.com/parallel-ai/parallel-ai-system
maintainers:
  - name: DevOps Team
    email: devops@parallel-ai.com
keywords:
  - ai
  - machine-learning
  - microservices
  - kubernetes
dependencies:
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "12.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: prometheus
    version: "15.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled