apiVersion: v1
kind: Namespace
metadata:
  name: parallel-ai-system
  labels:
    name: parallel-ai-system
    app.kubernetes.io/name: parallel-ai-system
    app.kubernetes.io/version: "1.0.0"
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: parallel-ai-staging
  labels:
    name: parallel-ai-staging
    app.kubernetes.io/name: parallel-ai-system
    app.kubernetes.io/version: "1.0.0"
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: parallel-ai-monitoring
  labels:
    name: parallel-ai-monitoring
    app.kubernetes.io/name: parallel-ai-system
    app.kubernetes.io/component: monitoring